# Generated by Django 2.2.5 on 2019-12-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_info',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('device_ip', models.CharField(help_text='设备IP', max_length=200, unique=True, verbose_name='设备IP')),
                ('device_name', models.CharField(help_text='设备名称', max_length=200, verbose_name='设备名称')),
                ('device_version', models.CharField(help_text='版本信息', max_length=200, verbose_name='设备版本')),
                ('tool_ip', models.CharField(help_text='工装设备IP', max_length=200, unique=True, verbose_name='工装设备IP')),
                ('tool_pc_ip', models.CharField(help_text='工装电脑IP', max_length=200, verbose_name='工装电脑IP')),
                ('daily_status', models.IntegerField(choices=[(0, '空闲'), (1, '使用中')], default=0, help_text='每日编译状态', verbose_name='每日编译状态')),
                ('use_status', models.IntegerField(choices=[(0, '空闲'), (1, '使用中')], default=0, help_text='设备使用状态', verbose_name='设备使用状态')),
                ('sd_status', models.IntegerField(choices=[(0, '无'), (1, '有')], default=0, help_text='SD卡状态', verbose_name='SD卡状态')),
                ('address', models.CharField(blank=True, default='', help_text='设备位置', max_length=200, null=True, verbose_name='设备位置')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
                'db_table': 'u_device_info',
            },
        ),
    ]
